name: Test CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin' # AdoptOpenJDK has been replaced with Temurin
      - name: Building project with Gradle
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - uses: actions/checkout@v2

        - name: Set up JDK 21
          uses: actions/setup-java@v2
          with:
            java-version: '21'
            distribution: 'temurin'
        - name: Testing
          working-directory: .
          run: |
            chmod +x gradlew
            ./gradlew test

        - name: Jacoco report
          id: jacoco
          working-directory: ./smart-home/Platform
          run: ./gradlew jacocoTestReport
